### PR TITLE
Dynamic cache options

### PR DESCRIPTION
**Pull request by appleton**
Allow passing route options to the `dynamicCache`.

I would like to add routes on a different origin domain to the `dynamicCache` array and I suspect other users may like to add other options to their route handlers too. This PR allows an alternate syntax to specifying the `dynamicCache` array:

``` js
dynamicCache: [
  {
    route: '/api/todos',
    options: { origin: 'https://api.example.com' }
  }
]
```

### CODE REVIEW

**Comment by jkleinsc** [comment]
@appleton looks good!  Thanks for the PR!

**Comment by appleton** [comment]
Thanks for merging! Any chance of a new npm release so I can start using it?

**Comment by jkleinsc** [comment]
@appleton Done.  0.0.9 has been published.  Thanks again for your PR.

**Comment by appleton** [comment]
Thank you!

**Pull request closed without merging**
