### PR TITLE
bump sw-toolbox and import correct map file

### PR DESCRIPTION
**Pull request by miguelcobain**
The `^3.1.1` dependency pulled the recently released `3.4.0` version.
It happens that in that version the map file changed name to `sw-toolbox.js.map`.

This fixes the dependency version and requires the correct file for that release.
A new release of broccoli-serviceworker should happen with this fix. Current version is broken for anyone that happens to pull sw-toolbox 3.4.0.

### CODE REVIEW

**Comment by laantorchaweb** [comment]
@jkleinsc I had issues on CI with this, rolling back to previous versions of the addon didn't seem to resolve the issue.

**Comment by ghost** [comment]
What's the plan with getting this merged? At the moment this it breaking my CI and I had to resort to using @miguelcobain 's branch as a dependency.

**Comment by gnowoel** [comment]
For now, we can add a fixed version of `sw-toolbox` in our project's `package.json`, like:

```
"sw-toolbox": "3.3.0"
```

This will force broccoli-serviceworker to use a previous version.

**Comment by jkleinsc** [comment]
@miguelcobain thanks for the PR!  @erkarl I just saw this now, so I am going to merge it in and push another release.  Thanks @gnowoel for the workaround.

**Comment by ghost** [comment]
Thanks @miguelcobain, @gnowoel & @jkleinsc

**Comment by jkleinsc** [comment]
@erkarl @miguelcobain, @gnowoel @laantorchaweb New version is now available on npm:

https://www.npmjs.com/package/broccoli-serviceworker

**Pull request merged**
