### PR TITLE
Add option to define if sourcemaps should be generated fixes #42

### LINKED ISSUE #42: Unable to build: missing sw-toolbox.js.map
I am unable to build my ember app with `ember build --environment production` since integrating `broccoli-serviceworker`. I get this error:

```
Build failed.
The Broccoli Plugin: [UglifyWriter] failed with:
Error: ENOENT: no such file or directory, open '/myapp/tmp/uglify_writer-input_base_path-CQGZ0XTh.tmp/0/sw-toolbox.js.map'
```

Environment:
- ember-cli: 2.9.1
- ember: 2.6.1
- broccoli-serviceworker: 0.1.3
- node: 4.6.0

### PR DESCRIPTION
**Pull request by urbany**
Option that fixes the problem described in https://github.com/jkleinsc/broccoli-serviceworker/issues/42#issuecomment-284185483

### CODE REVIEW

**Review by jkleinsc — CHANGES_REQUESTED** [review]
Thanks for the PR @urbany!  Would you mind updating the readme to reflect the change you've made here?

**Comment by urbany** [comment]
@jkleinsc sorry forgot about that. Done.

**Review by jkleinsc — APPROVED** [review]
Looks good to me @urbany!  I'll merge it in.

**Comment by urbany** [comment]
Thanks!

**Pull request merged**
