### PR TITLE
swIncludeFiles: join with ; when concatinating files

### LINKED ISSUE #34: swIncludeFiles: join with ; when concatinating files
Give my configuration includes

``` js
ENV.serviceWorker.swIncludeFiles = [
   'script1.js',
   'script2.js'
]
```

And both script1.js & script2.js content is 

``` js
(function (nr) {
  console.log(nr)
})(1)
```

Then Service Worker will thrown an "undefined is not a function"-esque error because brocolli-serviceworker simply concatenates the files, so it ends up to be

``` js
(function (nr) {
  console.log(nr)
})(1)
(function (nr) {
  console.log(nr)
})(1)
```

Which throws the error when you run in. 

I’ll send a PR in a minute to fix it

### PR DESCRIPTION
**Pull request by gr2m**
closes #34

### CODE REVIEW

**Comment by jkleinsc** [comment]
Thanks @gr2m for the PR!  I'll merge it in.

**Comment by gr2m** [comment]
Could you release a new version, too? I’m happy to help you setup [semantic-release](https://github.com/semantic-release/semantic-release) which automates releasing npm packages, by following a few commit conventions, it really removes a lot of chore worm from maintaining Node projects. Happy to give you a short intro, ping me :)

**Comment by jkleinsc** [comment]
@gr2m new version released.  semantic-release would be helpful to setup at some point, though right now there aren't any automated tests for this project which I think I would need first.

**Comment by gr2m** [comment]
ah yes, without tests semantic-release doesn’t make much sense

**Pull request merged**
