### PR TITLE
Clean content-for method

### PR DESCRIPTION
**Pull request by zzarcon**
Move ServiceWorker registration to another file in order to make it more readable and clean the `content-for` method /cc @miguelcobain

### CODE REVIEW

**Comment by zzarcon** [comment]
@jkleinsc if you like the approach, we can try to do the same for https://github.com/jkleinsc/broccoli-serviceworker/blob/master/lib/service-worker.js in order to make a bit more readable :)

**Comment by jkleinsc** [comment]
@zzarcon thanks for the PR! I do like the approach you have taken here.  As far as generating the service-worker, it's an approach usable there as well, but I will say that I am planning on using [Service Worker Toolbox](https://github.com/GoogleChrome/sw-toolbox) to clean up the code.  My thought is to use Service Worker Toolbox to do the heavy lifting around service workers and we would get the benefit of upstream fixes and improvements.

**Comment by miguelcobain** [comment]
I fully support this, especially for the service worker file. 

Doesn't the dependency need to be under `dependencies` instead of `devDependencies`?

**Comment by jkleinsc** [comment]
@miguelcobain Yes, it should be under dependencies.  I am going to update some of the other dependencies (broccoli-funnel, broccoli-kitchen-sink-helpers and broccoli-merge-trees) and I will update the package.json.

**Comment by zzarcon** [comment]
@miguelcobain @jkleinsc you're right! It should be in `dependencies` good catch!

**Comment by zzarcon** [comment]
@jkleinsc yeah using `sw-toolbox` makes a lot of sense for me too. I just proposed the `stringifile` + placeholder replacements for clean up a bit the code, but yeah your proposal it's more robust!

**Comment by marco-c** [comment]
> I will say that I am planning on using Service Worker Toolbox to clean up the code

https://github.com/GoogleChrome/sw-precache could suit your needs and is simpler than sw-toolbox.
There's also https://github.com/mozilla/oghliner, which would give you other features as well (not only offlining, but also deployment to GitHub Pages).

**Pull request merged**
